### ISSUE TITLE
能否支持以vercel搭建为网页端

### ISSUE THREAD

**Issue by inoribea** [yiktllw/XCMusic#1]
需要cookie是否可以用环境变量解决，不开启缓存是否可实现用vercel搭建？

**Comment by yiktllw** [comment]
本项目的前端代码使用了electron的api，网易云音乐api服务也是在electron程序中启动的，因此无法直接部署到vercel。

如果要部署到vercel，需要
- 将前端代码中的electron相关部分分离
- 在vercel上部署[NeteaseCloudMusicApi](https://github.com/yiktllw/NeteaseCloudMusicApi)。

我会在这几天把electron相关的部分分离出来。

**Comment by inoribea** [comment]
> 本项目的前端代码使用了electron的api，网易云音乐api服务也是在electron程序中启动的，因此无法直接部署到vercel。
> 
> 如果要部署到vercel，需要
> 
> * 将前端代码中的electron相关部分分离
> * 在vercel上部署[NeteaseCloudMusicApi](https://github.com/yiktllw/NeteaseCloudMusicApi)。
> 
> 我会在这几天把electron相关的部分分离出来。

非常感谢作者尝试支持！

**Comment by yiktllw** [comment]
已支持部署到vercel，详情见readme。
这是我的部署: [https://xc-music.vercel.app/](https://xc-music.vercel.app/)

**Comment by inoribea** [comment]
> 已支持部署到vercel，详情见readme。 这是我的部署: https://xc-music.vercel.app/

希望能将API替换修改成环境变量的方式，应该会增加易用性便于使用和保护隐私

**Comment by yiktllw** [comment]
> 希望能将API替换修改成环境变量的方式，应该会增加易用性便于使用和保护隐私

已实现，现在使用环境变量`VUE_APP_API`来配置api

**Comment by inoribea** [comment]
> > 希望能将API替换修改成环境变量的方式，应该会增加易用性便于使用和保护隐私
> 
> 已实现，现在使用环境变量`VUE_APP_API`来配置api

非常感谢实现！
