### ISSUE TITLE
请问是环境配置问题吗？？

### ISSUE THREAD

**Issue by Timearroworz** [yiktllw/XCMusic#2]
![IMG_20241109_003535_217.jpg](https://github.com/user-attachments/assets/d918c23a-8822-43c2-a25c-65288fb58691)

**Comment by yiktllw** [comment]
这个是NeteaseCloudMusicApi的问题，之前修过一次，最近由于更新了api版本才重新出现这个问题。

已经在[ncm-api](https://github.com/yiktllw/NeteaseCloudMusicApi/commit/6e067e15057ee51465732a558df63c2dc9aeb08e)中和[XCMusic的dev分支](https://github.com/yiktllw/XCMusic/commit/8ec616dc265c95696d4166a7de2ae1a97bde4394)中修复了此问题，同时也更新了0.2.1版本的release，重新安装就可以解决。

如果不想重新安装，就在你的图片所示的目录中(....\Temp\)手动新建一个anonymous_token文件即可。
